# Log 2024 01 
## 20240130
- When installing deepmind acme using:
    ```
    pip install dm-acme[jax,tf]
    ```
    error occured: 
    ```
    ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
    ```
    Solving it by:
    ```
    pip install dm-acme[jax,tf] --default-timeout=100
    ```
    ref: https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port

## 20240131
- DO NOT USE Python3.6 in conda environment to install deempmind acme through pip! It will install all the tensorflow from 2.3.4 to 2.61 (each one is about 400M) and all the tfp_nightly from 20230514 back to unclear version (it's 20221017 when I cancelled). It's terriable.
- On Ubuntu 22.04, venv or conda, can not succeed the acme examples according to the tutorials. It's so confusing.
- Finally, using tenforflow-2.8-gpu image with cuda11.2 and docker, it is realized to install and run examples correctly on Ubuntu 22.04. Below steps are very important:
    ```
    #[1] Install from the source code instead of pip and use python venv
    pip install .[jax,tf,testing,envs]

    #[2] Reduce the version of dm-haiku correspongding to the error:
    # File "path/anaconda3/envs/acme_jax/lib/python3.8/site-packages/haiku/_src/utils.py", line 42, in <module>
    # def auto_repr(cls: type[Any], *args, **kwargs) -> str:
    # TypeError: 'type' object is not subscriptable
    pip install dm-haiku==0.0.10
    
    #[3] Install other packages
    apt install libglfw3
    pip install mujoco_py
    # install mujoco210 to /root/.mujoco/
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mujoco210/bin
    pip install "cython<3"
    apt install libosmesa6-dev
    ```