# Log 2024 01 
## 20240130
- When installing deepmind acme using:
    ```
    pip install dm-acme[jax,tf]
    ```
    error occured: 
    ```
    ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.
    ```
    Solving it by:
    ```
    pip install dm-acme[jax,tf] --default-timeout=100
    ```
    ref: https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port